language: android
jdk: oraclejdk8
sudo: True

android:
  components:
  - platform-tools
  - tools
  - build-tools-19.0.1
  - android-22
  - extra-android-m2repository
  
  
script: 
  - sudo apt update
  - sudo apt install coreutils
  - sudo chomd -v 777 gradlew
  - ./gradlew connectedAndroidTest
