language: android
jdk: oraclejdk8
#sudo: false

android:
  components:
  - platform-tools
  - tools
  - build-tools-19.0.1
  - android-22
  - extra-android-m2repository
  
  
script: ./gradlew connectedAndroidTest
