language: android
jdk: oraclejdk8
sudo: True
dist: xenial

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

android:
  components:
    - platform-tools
    - tools
    - build-tools-26.0.1
    - android-19
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  

before_script:
  - sudo apt-get update
  - sudo wget https://services.gradle.org/distributions/gradle-5.2.1-bin.zip -P /tmp
  - sudo unzip -d /opt/gradle /tmp/gradle-*.zip
  - export GRADLE_HOME=/opt/gradle/gradle-5.2.1
  - export PATH=${GRADLE_HOME}/bin:${PATH}
  - cd $HOME
  - wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O $HOME/android-sdk.tgz
  - mkdir android
  - unzip android-sdk.tgz -d android/sdk
  - export PATH=$PATH:$HOME/android/sdk/tools:$HOME/android/sdk/tools/bin
  - cd build/watchdog1023/Lara-AI-Android-App 
  - echo y | sdkmanager 'ndk-bundle'
  - echo y | sdkmanager 'cmake;3.6.3155560'
  - export ANDROID_HOME=$HOME/android/sdk
  - export ANDROID_NDK_HOME=$HOME/android/sdk/ndk-bundle

script: 
  - gradle -v
  - gradle build
  
