language: android
jdk: oraclejdk8
sudo: True
dist: xenial

android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.1
  - android-19
  - extra-android-m2repository
  
  
script: 
  - sudo apt-get update
  - sudo apt-get install coreutils
  - sudo chmod -v 777 gradlew
  - sudo apt-get install gradle
  - pwd
  - ./gradlew assemble
  - gradle assemble
